### ISSUE TITLE
No module named 'zstandard'

### ISSUE THREAD

**Issue by Coloradohusky** [ArchiveTeam/google-sites-grab#4]
```
2020-10-30 02:58:31,994 - seesaw.warrior - DEBUG - Select project google-sites
2020-10-30 02:58:31,995 - seesaw.warrior - DEBUG - Start selected project google-sites (reinstall=False)
2020-10-30 02:58:31,995 - seesaw.warrior - DEBUG - Check project has update google-sites
2020-10-30 02:58:31,998 - seesaw.warrior - DEBUG - git fetch
2020-10-30 02:58:32,418 - seesaw.warrior - DEBUG - False
2020-10-30 02:58:32,419 - seesaw.warrior - DEBUG - Clone project google-sites /home/warrior/projects/google-sites
2020-10-30 02:58:32,422 - seesaw.warrior - DEBUG - Cloning version 7c4eace
2020-10-30 02:58:32,422 - seesaw.warrior - DEBUG - Load pipeline /data/data/projects/google-sites-7c4eace/pipeline.py
2020-10-30 02:58:32,422 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2020-10-30 02:58:32,422 - seesaw.warrior - DEBUG - Executing pipeline
2020-10-30 02:58:32,425 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 737, in start_selected_project
    pipeline_path, {"downloader": self.downloader})
  File "/home/warrior/warrior-code2/src/seesaw/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 28, in <module>
ModuleNotFoundError: No module named 'zstandard'
2020-10-30 02:58:32,425 - seesaw.warrior - WARNING - Project google-sites did not install correctly and we're ignoring this problem.
```

However, `zstandard` is installed:
```
C:\WINDOWS\system32>pip install --upgrade zstandard
Requirement already up-to-date: zstandard in c:\users\riley\appdata\local\programs\python\python38\lib\site-packages (0.14.0)
Requirement already satisfied, skipping upgrade: cffi>=1.11 in c:\users\riley\appdata\local\programs\python\python38\lib\site-packages (from zstandard) (1.14.0)
Requirement already satisfied, skipping upgrade: pycparser in c:\users\riley\appdata\local\programs\python\python38\lib\site-packages (from cffi>=1.11->zstandard) (2.20)
```

On Windows 10.

**Comment by Coloradohusky** [comment]
Going through other projects, and that seems to be the same error as lots of other ones:
-Github
-YouTube Playlist Notes
-Reddit (Test)
-Pastebin
-Mercurial

URLTeam 2 and Angelfire work fine, though

**Comment by ASGdev** [comment]
You can directly use the docker image : `docker run warcforceone/google-sites-grab:latest [username]`

**Comment by Coloradohusky** [comment]
Ooh there’s a docker image, that’s great! Thanks!

**Comment by ASGdev** [comment]
But now the latest version has an error by me. I notified the problem in the IRC.

```
Looking for Wget+AT in ./wget-at
./wget-at: Incorrect Wget+AT version (want ['GNU Wget 1.20.3-at.20200902.01', 'GNU Wget 1.20.3-at.20200919.01']).
Traceback (most recent call last):
  File "/usr/local/bin/run-pipeline3", line 13, in <module>
    main()
  File "/usr/local/lib/python3.8/site-packages/seesaw/script/run_pipeline.py", line 223, in main
    runner = init_runner(args)
  File "/usr/local/lib/python3.8/site-packages/seesaw/script/run_pipeline.py", line 252, in init_runner
    (project, pipeline) = load_pipeline(args.pipeline, context)
  File "/usr/local/lib/python3.8/site-packages/seesaw/script/run_pipeline.py", line 39, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 50, in <module>
```

It is ok for you ?
